import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import '../styles/Reports.css';

const nice=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const money=(value,currency='USD')=>new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:2}).format(Number(value||0));
const percent=value=>`${Number(value||0).toFixed(1)}%`;
const csvCell=value=>`"${String(value??'').replaceAll('"','""')}"`;

export default function Reports({organization,onNavigate}){
 const today=new Date().toISOString().slice(0,10),yearStart=`${new Date().getFullYear()}-01-01`;
 const [state,setState]=useState({runs:[],exceptions:[],workspaces:[],rules:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[workspace,setWorkspace]=useState('all'),[from,setFrom]=useState(yearStart),[to,setTo]=useState(today),[report,setReport]=useState('summary');
 const load=useCallback(async()=>{if(!organization?.id)return;setLoading(true);setError('');const org=organization.id;const [runs,exceptions,workspaces,rules]=await Promise.all([
  supabase.from('reconciliation_runs').select('id,name,workspace_id,period_start,period_end,status,total_transactions,matched_transactions,average_confidence,reconciled_amount,outstanding_difference,created_at,workspace:workspaces(name,base_currency)').eq('organization_id',org).order('period_end',{ascending:true}),
  supabase.from('exceptions').select('id,workspace_id,category,priority,status,financial_impact,currency,due_at,resolved_at,created_at,workspace:workspaces(name)').eq('organization_id',org).order('created_at',{ascending:false}),
  supabase.from('workspaces').select('id,name,base_currency,status').eq('organization_id',org).order('name'),
  supabase.from('reconciliation_rules').select('id,status,workspace_id').eq('organization_id',org)
 ]);const failed=[runs,exceptions,workspaces,rules].find(result=>result.error);if(failed)setError(failed.error.message);else setState({runs:runs.data||[],exceptions:exceptions.data||[],workspaces:workspaces.data||[],rules:rules.data||[]});setLoading(false)},[organization]);
 useEffect(()=>{load()},[load]);
 const data=useMemo(()=>{const inRange=value=>{if(!value)return true;const day=value.slice(0,10);return(!from||day>=from)&&(!to||day<=to)},scope=item=>workspace==='all'||item.workspace_id===workspace;return{runs:state.runs.filter(run=>scope(run)&&inRange(run.period_end||run.created_at)),exceptions:state.exceptions.filter(item=>scope(item)&&inRange(item.created_at))}},[state,workspace,from,to]);
 const metrics=useMemo(()=>{const total=data.runs.reduce((sum,run)=>sum+Number(run.total_transactions||0),0),matched=data.runs.reduce((sum,run)=>sum+Number(run.matched_transactions||0),0),difference=data.runs.reduce((sum,run)=>sum+Math.abs(Number(run.outstanding_difference||0)),0),open=data.exceptions.filter(item=>!['resolved','ignored'].includes(item.status)),resolved=data.exceptions.filter(item=>item.status==='resolved'),confidence=data.runs.filter(run=>run.average_confidence!=null);return{total,matched,rate:total?matched/total*100:0,difference,open,resolved,confidence:confidence.length?confidence.reduce((sum,run)=>sum+Number(run.average_confidence),0)/confidence.length:0}},[data]);
 const trend=useMemo(()=>data.runs.slice(-8).map(run=>({...run,rate:run.total_transactions?Number(run.matched_transactions||0)/Number(run.total_transactions)*100:0})),[data.runs]);
 const category=useMemo(()=>Object.entries(data.exceptions.reduce((groups,item)=>({...groups,[item.category]:(groups[item.category]||0)+1}),{})).sort((a,b)=>b[1]-a[1]).slice(0,6),[data.exceptions]);
 const exportCsv=()=>{const rows=report==='exceptions'?[['Exception ID','Workspace','Category','Priority','Status','Financial impact','Currency','Created'],...data.exceptions.map(item=>[item.id,item.workspace?.name,item.category,item.priority,item.status,item.financial_impact,item.currency,item.created_at])]:[['Run ID','Run','Workspace','Period start','Period end','Status','Transactions','Matched','Match rate','Average confidence','Outstanding difference'],...data.runs.map(run=>[run.id,run.name,run.workspace?.name,run.period_start,run.period_end,run.status,run.total_transactions,run.matched_transactions,run.total_transactions?Number(run.matched_transactions||0)/Number(run.total_transactions)*100:0,run.average_confidence,run.outstanding_difference])];const blob=new Blob([rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`axiom-${report}-${today}.csv`;link.click();URL.revokeObjectURL(url)};
 if(loading)return <div className="reports-loading"><span/>Preparing reports…</div>;
 return <main className="reports-page">
  <section className="reports-heading"><div><small>FINANCIAL CONTROL & ANALYTICS</small><h2>Reports center</h2><p>Analyze reconciliation performance, outstanding exposure, and exception resolution for {organization?.name}.</p></div><div><button onClick={load}>Refresh</button><button className="primary" onClick={exportCsv} disabled={!data.runs.length&&!data.exceptions.length}>Export CSV</button></div></section>
  {error&&<div className="reports-alert"><b>Reports could not load.</b><span>{error}</span><button onClick={load}>Retry</button></div>}
  <section className="report-library">{[['summary','Reconciliation summary'],['performance','Match performance'],['exceptions','Exceptions aging'],['usage','Usage report']].map(([id,label])=><button className={report===id?'active':''} onClick={()=>setReport(id)} key={id}><i>{id.slice(0,2).toUpperCase()}</i><span><b>{label}</b><small>{id==='summary'?'Balances and completion':id==='performance'?'Match rate and confidence':id==='exceptions'?'Open items and exposure':'Transaction volumes'}</small></span></button>)}</section>
  <section className="report-filters"><label>Workspace<select value={workspace} onChange={event=>setWorkspace(event.target.value)}><option value="all">All workspaces</option>{state.workspaces.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>From<input type="date" value={from} max={to||today} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} min={from} max={today} onChange={event=>setTo(event.target.value)}/></label><span>{data.runs.length} runs · {data.exceptions.length} exceptions</span></section>
  <section className="report-kpis"><article><small>Transactions processed</small><b>{metrics.total.toLocaleString()}</b><span>{metrics.matched.toLocaleString()} matched</span></article><article className="good"><small>Match rate</small><b>{percent(metrics.rate)}</b><span>{percent(metrics.confidence)} average confidence</span></article><article className={metrics.open.length?'warning':'good'}><small>Open exceptions</small><b>{metrics.open.length}</b><span>{metrics.resolved.length} resolved in range</span></article><article className={metrics.difference?'warning':'good'}><small>Outstanding difference</small><b>{money(metrics.difference,organization?.base_currency)}</b><span>Absolute value across runs</span></article></section>
  <section className="report-grid"><article className="report-card trend-card"><header><div><small>PERIOD TREND</small><h3>Match performance</h3></div><span>Last {trend.length} runs</span></header>{trend.length?<div className="trend-chart">{trend.map(run=><div key={run.id} title={`${run.name}: ${percent(run.rate)}`}><span><i style={{height:`${Math.max(run.rate,3)}%`}}/></span><b>{percent(run.rate)}</b><small>{run.period_end?new Date(`${run.period_end}T00:00:00`).toLocaleDateString(undefined,{month:'short',year:'2-digit'}):'Draft'}</small></div>)}</div>:<Empty onClick={()=>onNavigate('reconciliation')}/>}</article>
   <article className="report-card category-card"><header><div><small>EXCEPTION MIX</small><h3>Exceptions by category</h3></div></header>{category.length?<div>{category.map(([name,count])=><p key={name}><span><b>{nice(name)}</b><small>{count} item{count===1?'':'s'}</small></span><i><em style={{width:`${count/category[0][1]*100}%`}}/></i></p>)}</div>:<div className="report-clean"><b>No exceptions</b><span>No exception activity exists in this reporting range.</span></div>}</article>
  </section>
  <section className="report-card report-table"><header><div><small>{report==='exceptions'?'EXCEPTION DETAIL':'RUN DETAIL'}</small><h3>{report==='exceptions'?'Exceptions aging':'Reconciliation results'}</h3></div></header>{report==='exceptions'?<ExceptionTable items={data.exceptions} currency={organization?.base_currency}/>:<RunTable runs={data.runs} currency={organization?.base_currency}/>}</section>
 </main>
}
function RunTable({runs,currency}){return runs.length?<div className="report-table-wrap"><table><thead><tr><th>Run</th><th>Workspace</th><th>Period</th><th>Status</th><th className="numeric">Transactions</th><th className="numeric">Match rate</th><th className="numeric">Difference</th></tr></thead><tbody>{[...runs].reverse().map(run=><tr key={run.id}><td><b>{run.name}</b></td><td>{run.workspace?.name||'—'}</td><td>{run.period_end||'—'}</td><td><span className={`report-status ${run.status}`}>{nice(run.status)}</span></td><td className="numeric">{Number(run.total_transactions||0).toLocaleString()}</td><td className="numeric">{percent(run.total_transactions?Number(run.matched_transactions||0)/Number(run.total_transactions)*100:0)}</td><td className="numeric">{money(run.outstanding_difference,run.workspace?.base_currency||currency)}</td></tr>)}</tbody></table></div>:<Empty/>}
function ExceptionTable({items,currency}){return items.length?<div className="report-table-wrap"><table><thead><tr><th>Exception</th><th>Workspace</th><th>Category</th><th>Priority</th><th>Status</th><th>Age</th><th className="numeric">Impact</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><b>EX-{item.id.slice(0,8).toUpperCase()}</b></td><td>{item.workspace?.name||'—'}</td><td>{nice(item.category)}</td><td>{nice(item.priority)}</td><td><span className={`report-status ${item.status}`}>{nice(item.status)}</span></td><td>{Math.max(0,Math.floor((Date.now()-new Date(item.created_at))/86400000))} days</td><td className="numeric">{money(item.financial_impact,item.currency||currency)}</td></tr>)}</tbody></table></div>:<Empty/>}
function Empty({onClick}){return <div className="reports-empty"><i>RP</i><b>No report data in this range</b><span>Adjust the filters or process a reconciliation to generate reporting data.</span>{onClick&&<button onClick={onClick}>Start reconciliation</button>}</div>}
